# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fccb95f17a634129ed2d50cede3fd247159e98d5b3c1941ebc6206de444bcb3c16e45f7351e7e67acf21007cf6e519fdfe865861bf72473e0993b4f72ae68382

test:
  secret_key_base: a60fe26c6a90cca0ea3405d3084eb2a307d36579a290bad9b5ad39c61bb3f730930dd610d878604ea9f3a3b0aefc2bd5aae7c0974e88844d933634e3c2093c16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
